### PR TITLE
chore: prepare for ownership claim

### PR DESCRIPTION
**Pull request by STRRL**
Signed-off-by: STRRL <im@strrl.dev>

ready for setup [Ownership Claim](https://artifacthub.io/docs/topics/repositories/#ownership-claim) on Artifact Hub.

I have tried to connect the original publisher "wuxiaohui" by slack and email, but I got no response.

I think ownership claim could help us.

### CODE REVIEW

**Comment by STRRL** [comment]
also relates to https://github.com/chaos-mesh/chaos-mesh/pull/3355

**Review by YangKeao — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
